-- ============================================================================
--  Les tables TELLES QU'ELLES SONT VRAIMENT, avant la migration 001.
-- ============================================================================
--  RELEVÉ SUR LE PROJET le 10 août 2026 (information_schema.columns), pas
--  supposé. La première version de ce fichier était une reconstitution de
--  mémoire : elle déclarait « id uuid » partout. C'était faux, et le banc a
--  donc validé du code qui aurait cassé la création de compte en Première —
--  où les identifiants sont des bigint.
--
--  LES TROIS NIVEAUX N'ONT PAS LA MÊME STRUCTURE. C'est le fait central que
--  ce fichier doit préserver :
--
--      Terminale  eleves.id        uuid      resultats.eleve_id      uuid
--      Première   eleves_1ere.id   BIGINT    resultats_1ere.eleve_id BIGINT
--      Seconde    eleves_2nde.id   uuid      resultats_2nde.eleve_id uuid
--
--  Les types des colonnes de notes diffèrent aussi d'un niveau à l'autre
--  (score numeric ici, integer là ; duration_sec numeric en Terminale). Ils
--  sont reproduits à l'identique : c'est ce genre d'écart qui fait qu'un
--  contrôle passe sur un niveau et casse sur un autre.
--
--  Si la structure du projet change, RELEVEZ-LA À NOUVEAU plutôt que de
--  corriger ce fichier de tête. La requête est dans supabase/LISEZMOI.md.
-- ============================================================================

-- ---------------------------------------------------------------- TERMINALE
create table if not exists public.eleves (
  id uuid primary key default gen_random_uuid(),
  prenom text not null,
  pin text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.resultats (
  id uuid primary key default gen_random_uuid(),
  eleve_id uuid not null references public.eleves(id) on delete cascade,
  score integer, total integer, percent integer,
  duration_sec numeric,                       -- numeric ici, integer ailleurs
  details jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.parametres (
  id integer primary key,
  valeurs jsonb
);

-- ----------------------------------------------------------------- PREMIÈRE
-- Le seul niveau en bigint. C'est lui que la supposition « tout est uuid »
-- aurait cassé, et lui seul.
create table if not exists public.eleves_1ere (
  id bigint generated by default as identity primary key,
  prenom text not null,
  pin text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.resultats_1ere (
  id bigint generated by default as identity primary key,
  eleve_id bigint not null references public.eleves_1ere(id) on delete cascade,
  score numeric, total integer, percent integer, duration_sec integer,
  details jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.parametres_1ere (
  id integer primary key,
  valeurs jsonb
);

-- ------------------------------------------------------------------ SECONDE
create table if not exists public.eleves_2nde (
  id uuid primary key default gen_random_uuid(),
  prenom text not null,
  pin text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.resultats_2nde (
  id uuid primary key default gen_random_uuid(),
  eleve_id uuid not null references public.eleves_2nde(id) on delete cascade,
  score numeric, total integer, percent numeric, duration_sec integer,
  details jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.parametres_2nde (
  id integer primary key,
  valeurs jsonb
);

-- Les droits que Supabase accorde par défaut : sans RLS, ils suffisent à tout
-- lire et à tout écrire depuis le navigateur. C'est l'état actuel.
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
