-- ============================================================================
--  Les tables TELLES QU'ELLES SONT VRAIMENT, avant la migration 001.
-- ============================================================================
--  RELEVÉ SUR LE PROJET le 10 août 2026 (information_schema.columns), pas
--  supposé. La première version de ce fichier était une reconstitution de
--  mémoire : elle déclarait « id uuid » partout. C'était faux, et le banc a
--  donc validé du code qui aurait cassé la création de compte en Première —
--  où les identifiants sont des bigint.
--
--  LES TROIS NIVEAUX N'ONT PAS LA MÊME STRUCTURE. C'est le fait central que
--  ce fichier doit préserver :
--
--      Terminale  eleves.id        uuid      resultats.eleve_id      uuid
--      Première   eleves_1ere.id   BIGINT    resultats_1ere.eleve_id BIGINT
--      Seconde    eleves_2nde.id   uuid      resultats_2nde.eleve_id uuid
--
--  Les types des colonnes de notes diffèrent aussi d'un niveau à l'autre
--  (score numeric ici, integer là ; duration_sec numeric en Terminale). Ils
--  sont reproduits à l'identique : c'est ce genre d'écart qui fait qu'un
--  contrôle passe sur un niveau et casse sur un autre.
--
--  Si la structure du projet change, RELEVEZ-LA À NOUVEAU plutôt que de
--  corriger ce fichier de tête. La requête est dans supabase/LISEZMOI.md.
-- ============================================================================

-- ---------------------------------------------------------------- TERMINALE
create table if not exists public.eleves (
  id uuid primary key default gen_random_uuid(),
  prenom text not null,
  pin text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.resultats (
  id uuid primary key default gen_random_uuid(),
  eleve_id uuid not null references public.eleves(id) on delete cascade,
  score integer, total integer, percent integer,
  duration_sec numeric,                       -- numeric ici, integer ailleurs
  details jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.parametres (
  id integer primary key,
  valeurs jsonb
);

-- ----------------------------------------------------------------- PREMIÈRE
-- Le seul niveau en bigint. C'est lui que la supposition « tout est uuid »
-- aurait cassé, et lui seul.
create table if not exists public.eleves_1ere (
  id bigint generated by default as identity primary key,
  prenom text not null,
  pin text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.resultats_1ere (
  id bigint generated by default as identity primary key,
  eleve_id bigint not null references public.eleves_1ere(id) on delete cascade,
  score numeric, total integer, percent integer, duration_sec integer,
  details jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.parametres_1ere (
  id integer primary key,
  valeurs jsonb
);

-- ------------------------------------------------------------------ SECONDE
create table if not exists public.eleves_2nde (
  id uuid primary key default gen_random_uuid(),
  prenom text not null,
  pin text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.resultats_2nde (
  id uuid primary key default gen_random_uuid(),
  eleve_id uuid not null references public.eleves_2nde(id) on delete cascade,
  score numeric, total integer, percent numeric, duration_sec integer,
  details jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.parametres_2nde (
  id integer primary key,
  valeurs jsonb
);

grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- ============================================================================
--  LES NEUF POLITIQUES GRANDES OUVERTES — relevées sur le projet le 11 août 2026
-- ============================================================================
--  La RLS était DÉJÀ active, mais chaque table portait une politique
--  « for all … using (true) with check (true) » ouverte à anon. PostgreSQL
--  combine les politiques permissives par un OU : il suffit qu'UNE SEULE
--  autorise pour que l'accès passe. Une politique pareille annule donc toutes
--  celles qu'on pourrait ajouter à côté.
--
--  La migration 001 se refusait à toucher aux politiques qu'elle n'avait pas
--  écrites — prudence légitime, mais qui laissait la porte grande ouverte : la
--  base restait entièrement lisible et modifiable après son passage. C'est ce
--  que 002 corrige, et c'est ce que ce fichier permet enfin de démontrer.
--
--  Les trois niveaux ont trois conventions de nommage différentes. Elles sont
--  reproduites telles quelles : un correctif qui filtrerait sur « _all » en
--  raterait six sur neuf.
-- ============================================================================
alter table public.eleves           enable row level security;
alter table public.eleves_1ere      enable row level security;
alter table public.eleves_2nde      enable row level security;
alter table public.resultats        enable row level security;
alter table public.resultats_1ere   enable row level security;
alter table public.resultats_2nde   enable row level security;
alter table public.parametres       enable row level security;
alter table public.parametres_1ere  enable row level security;
alter table public.parametres_2nde  enable row level security;

create policy "acces classe - eleves"        on public.eleves          for all to anon using (true) with check (true);
create policy "acces classe - resultats"     on public.resultats       for all to anon using (true) with check (true);
create policy "acces classe - parametres"    on public.parametres      for all to anon using (true) with check (true);

create policy eleves_1ere_all      on public.eleves_1ere     for all to anon, authenticated using (true) with check (true);
create policy resultats_1ere_all   on public.resultats_1ere  for all to anon, authenticated using (true) with check (true);
create policy parametres_1ere_all  on public.parametres_1ere for all to anon, authenticated using (true) with check (true);

create policy acces_appli_eleves_2nde     on public.eleves_2nde     for all to public using (true) with check (true);
create policy acces_appli_resultats_2nde  on public.resultats_2nde  for all to public using (true) with check (true);
create policy acces_appli_parametres_2nde on public.parametres_2nde for all to public using (true) with check (true);
